version: 2
jobs:
  build:
    working_directory: ~/workspace

    docker:
      - image: docker:17.03-git

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Docker Build
          command: docker build -t intimatemerger/mecab-ipadic-neologd:${TAG-latest} .

      - deploy:
          name: Push to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
              docker push intimatemerger/mecab-ipadic-neologd:${TAG-latest}
            fi

      - deploy:
          name: Push to Docker Hub - onbuild
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t intimatemerger/mecab-ipadic-neologd:onbuild onbuild
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
              docker push intimatemerger/mecab-ipadic-neologd:onbuild
            fi
